### ISSUE TITLE
GUI Locked after completion

### ISSUE THREAD

**Issue by cjhaviland** [tadpoleloop/idle_apocalypse_event_planner#27]
Whenever processing if completed the GUI is completely locked. 

- I can move the sliders, but the costs and levels do not change
- The create_plan button does nothing.

Not sure if this is intentional, or a limitation of MyBinder, but it could be nicer to either disable everything above after a run is completed. Or allow for a re-run after changing the sliders.

**Comment by tadpoleloop** [comment]
This is due to timing out with mybinder. The server is no longer alive of you are inactive for too long.

I could add a dummy background process to keep it alive, but it wouldn't be good to just have the server idle for no reason. You'll have to spin up the server again if you wait too long.
